// <auto-generated />
using System;
using ControllerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControllerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControllerAPI.Models.Pants", b =>
                {
                    b.Property<int>("PantsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PantsId"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int?>("SizeWaist")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PantsId");

                    b.ToTable("Pants");

                    b.HasData(
                        new
                        {
                            PantsId = 1,
                            Brand = "MyBrand",
                            Color = "Blue",
                            Gender = "Male",
                            Price = 70,
                            Size = 170,
                            SizeWaist = 100,
                            Type = "Jeans"
                        },
                        new
                        {
                            PantsId = 2,
                            Brand = "YourBrand",
                            Color = "Gray",
                            Gender = "Female",
                            Price = 60,
                            Size = 160,
                            SizeWaist = 80,
                            Type = "Trousers"
                        },
                        new
                        {
                            PantsId = 3,
                            Brand = "TheirBrand",
                            Color = "Black",
                            Gender = "Kid",
                            Price = 40,
                            Size = 110,
                            SizeWaist = 55,
                            Type = "Shorts"
                        });
                });

            modelBuilder.Entity("ControllerAPI.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "My Brand",
                            Color = "Blue",
                            Gender = "Male",
                            Price = 30.0,
                            Size = 170
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "My Brand",
                            Color = "Black",
                            Gender = "Female",
                            Price = 35.0,
                            Size = 150
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "Your Brand",
                            Color = "Red",
                            Gender = "Male",
                            Price = 40.0,
                            Size = 180
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "Your Brand",
                            Color = "Green",
                            Gender = "Female",
                            Price = 20.0,
                            Size = 160
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
